### PR TITLE
Infobox control

### PR DESCRIPTION
**Pull request by ryanjhodge**
Are you folks happy with the `infoBox` property name in the NPMap config object?  When I was updating the API doc, I realized `infoboxControl` is probably more consistent.

I defined all the `L.npmap.tooltip()` methods in `L.npmap.control.infobox()`, thinking in terms of an OOP interface.  Is it worth documenting this "tooltip" interface similar to how the [leaflet docs](http://leafletjs.com/reference.html#icontrol) document them?

I wanted this feature for this Vegetation Inventory Project Map I'm working on. [Dataset preview](https://api.tiles.mapbox.com/v4/ryanjhodge.23f33aa8/page.html?access_token=pk.eyJ1Ijoicnlhbmpob2RnZSIsImEiOiJ5clRfMjRRIn0.KldXlC8cT9zpaQGY_YSOGQ#13/34.0394/-116.3559)

### CODE REVIEW

**Comment by nateirwin** [comment]
This looks great, Ryan! I did have one thought though: Might it make more sense to add a new config to `L.npmap.tooltip`, something like `pinPosition: 'topright'`, and then merge the two controls into one? I honestly haven't done an in-depth comparison between the tooltip code and the infobox code, but wanted to ask what you thought about that.

**Comment by ryanjhodge** [comment]
I think that was the initial path I went down, which was to intercept `tooltip.setPosition()` from being called and set the tooltip position to one of the corners.  I got that working, but quickly found that since `L.npmap.tooltip` extends `L.Class` and not `L.Control` the tooltip would appear on top of the other controls.

That set me down the path of writing the infobox control, which extends `L.Control`.  This way the infobox gets added to the `leaflet-control-container` div elements, instead of `leaflet-tooltip-container`

capture

**Comment by ryanjhodge** [comment]
Although, I might not fully understand your suggestion, specifically the merge the two controls into one part.

**Comment by nateirwin** [comment]
That makes sense. Thanks for the explanation. Given your explanation, I think it makes sense to keep the two controls separated.

A few more things:

- Rather than updating the "tooltips.html" example, can you create a new example, "infobox.html"?
- Yes, the config property should be `infoboxControl` so it is consistent with the other controls. Would you mind changing this? (The docs will need to be updated too.)

Once those two changes are made, we'll merge!

**Comment by ryanjhodge** [comment]
Done.

**Comment by nateirwin** [comment]
Looks great!

**Pull request merged**
