### PR TITLE
Switcher zoom level issues

### PR DESCRIPTION
**Pull request by ryanjhodge**
- If the map's current zoom level is outside of the selected baselayer's zoom range, sets the map's zoom level to the min/max zoom level of the selected baselayer
- Set's the map's `maxZoom` option to the selected baselayer's `maxZoom`, if not specified by baselayer then set map's `maxZoom` to 19

### CODE REVIEW

**Comment by nateirwin** [comment]
Hi, @ryanjhodge, this looks good! I did think of one thing that we may need to cleanup before merging this though: I think we need to handle the case where a `maxZoom` is set on the map itself and then a basemap is toggled on that has a `maxZoom` set that is higher than the one set for the map.

Does that make sense?

We may need to handle this for `minZoom` too.

**Comment by ryanjhodge** [comment]
Yes that makes a lot of sense.  I will defiantly get to this during the weekend.

**Comment by ryanjhodge** [comment]
I think this code is suffering from the same "race condition" as [this Leaflet issue.](https://github.com/Leaflet/Leaflet/issues/2021)

Landsat Live covers a zoom range of 7-12.  When switching to Landsat live from another baselayer that is outside this range, Leaflet sometimes freezes.  It almost always happens when the map is at a zoom level close to the min or max zoom of Landsat Live (e.g. 5-6, 13-14). When it freezes, the map cannot be panned or zoomed using the controls or mouse.

According to the referenced leaflet issue, it seems to happen when `setZoom()`, `setView()`, and `fitBounds()` are called just after the layer is instantiated.

Here's a gif showing the freezing behavior.

test11


The workaround that is suggested in the issue discussion resolves this problem. Just replace [switcher.js#L113](https://github.com/nationalparkservice/npmap.js/blob/switcher-zoom/src/control/switcher.js#L113) with the following code block:
```
setTimeout(function(map, baselayer) {
  map.setView(map.getCenter(), baselayer.minZoom);
}, 200, this._map, baseLayer);
```

**Comment by ryanjhodge** [comment]
Reading through the leaflet issue it is still unclear to me whether their fix was backported to leaflet stable.  I'm going to see if switching to leaflet 1.0, fixes this.

**Comment by nateirwin** [comment]
I have a branch that I'm working on to upgrade to 1.0 here: https://github.com/nationalparkservice/npmap.js/tree/leaflet-1.0.

**Comment by ryanjhodge** [comment]
Switching to Leaflet/stable nor Leaflet/master fixed this problem.  I had to build leaflet manually in `node_modules/leaflet` after installing npmap.js.   The previously mentioned workaround fixes it though.

**Comment by nateirwin** [comment]
So there isn't a fix in Leaflet for this? If not, I don't understand why building Leaflet manually would be necessary?

**Comment by ryanjhodge** [comment]
Oh it was because they stopped tracking 'leaflet-src.js' in the dist folder
of the leaflet github repo.  I think it comes prebuilt from npm under when
the leaflet entry of 'package.json' is set to '0.7.3', but after changing
that to a github repo url it has to be built using jake to generate the
'leaflet-src.js' file.

**Comment by ryanjhodge** [comment]
https://github.com/Leaflet/Leaflet/issues/1354

See there. About halfway down there is an S3 amazon aws link to where they host the dist now. Probably a way to pull from there instead of building manually.

http://leaflet-cdn.s3.amazonaws.com/build/leaflet-master.zip

http://leaflet-cdn.s3.amazonaws.com/build/leaflet-stable.zip

**Comment by nateirwin** [comment]
Ah, gotcha. I'm going to go ahead and merge then. Thanks!

**Comment by ryanjhodge** [comment]
After working on the `leaflet-1.0` branch yesterday, I realized I didn't test to see if `leaflet-1.0.0-beta.1` fixes the race condition, I only tried the leaflet `stable` and `master` branches. I experimented by removing the work-around for the race condition (9173e1a6138c42843b9e261df101f4694d05af41) on my local `leaflet-1.0` branch and I'm not experiencing the freezing issue.

I'll add a commit that removes the workaround on the `leaflet-1.0` branch, so the workaround wil get removed when we officially move to leaflet 1.0.

**Comment by nateirwin** [comment]
Great!

**Comment by ryanjhodge** [comment]
Leaflet@0.7.5 fixes the race condition.  I just published a `leaflet-0.7.5` branch in which I upgraded to Leaflet 0.7.5 and reverted the workaround for the race condition.  Opening a pull request now.

**Pull request merged**
